# SPDX-FileCopyrightText: © 2023 Jinwoo Park (pmnxis@gmail.com)
#
# SPDX-License-Identifier: CC0-1.0

# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
# "nightly-2023-08-19" is used for embassy-rs ( rev = "ecc305bbfe1007f9daa4d6a585dfc66f6ca69218" )
# But consider `const impl` feature issue, use 08-24
# details 1 : https://github.com/rust-lang/rust/issues/114808
# details 2 : https://github.com/rust-lang/rust/pull/114781
channel = "nightly-2023-08-24"
